### ISSUE TITLE
erro ao iniciar

### ISSUE THREAD

**Issue by hilner** [codeedu/maratona-microsservico-simulador#1]
docker-compose  up
Recreating maratona-microsservico-simulador_rabbit_1 ... error

ERROR: for maratona-microsservico-simulador_rabbit_1  Cannot start service rabbit: driver failed programming external connectivity on endpoint maratona-microsservico-simulador_rabbit_1 (d55735e8721aa81a4d99f653bc6ab198cac36bec26cd61359473264b86fc534a): Bind for 0.0.0.0:15672 failed: port is already allocated

ERROR: for rabbit  Cannot start service rabbit: driver failed programming external connectivity on endpoint maratona-microsservico-simulador_rabbit_1 (d55735e8721aa81a4d99f653bc6ab198cac36bec26cd61359473264b86fc534a): Bind for 0.0.0.0:15672 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Comment by danielsahara** [comment]
este docker-compose eh do rabbit... o mesmo rabbit do order, por isso está dando que a porta está sendo usada. 
Rode o simulador local, este projeto está sem docker.
